# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
  containers:
    - container: cd
      image: wcarlsen/saml2aws-kubernetes-service-connection:latest
      env:
        SAML2AWS_PASSWORD: $(SAML2AWS_PASSWORD)

stages:
# Continuous Deployment steps
- stage: CD
  pool:
    vmImage: 'ubuntu-latest'  

  jobs:
  - job: "bla"
    container: cd
    steps:
    - task: Kubernetes@1
      displayName: 'Apply manifests'
      inputs:
        connectionType: Kubernetes Service Connection
        kubernetesServiceEndpoint: 'Kubernetes-wicar-test'
        namespace: 'sandbox-wicar-ypvvv'
        command: apply
        arguments: '-f $(System.DefaultWorkingDirectory)/k8s/'